/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account with email + password.
         * @description Creates an unverified account and sends a verification email via SMTP. Email is trimmed and compared case-insensitively; must be unique. Password must be at least 8 characters. No auto-login.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with local credentials and receive a bearer token.
         * @description Returns a bearer JWT on success. Unverified accounts are rejected with 403.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out the current session (client discards the token).
         * @description Bearer-authenticated. With stateless JWTs the client discards the token; the endpoint exists for symmetry and any server-side session cleanup.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify an email address using a single-use token.
         * @description Public. The single-use token is passed as a query parameter (permitted for the verification token only). Tokens expire after 24h and are single-use. On success the backend responds with a 302 redirect to `${APP_BASE_URL}/login` (no auto-login). See ADR-0009 statement 12.
         */
        get: operations["verifyEmail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a fresh verification email.
         * @description Public. Issues a new verification token (invalidating prior unused tokens) and sends a new email. Responds 202 regardless of whether the address maps to an existing unverified account, to avoid account enumeration.
         */
        post: operations["resendVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all teams. */
        get: operations["listTeams"];
        put?: never;
        /** Create a team. */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team identifier. */
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        /** Get a single team. */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        /**
         * Delete a team.
         * @description Fails with 409 if the team still contains tickets or epics (no cascade).
         */
        delete: operations["deleteTeam"];
        options?: never;
        head?: never;
        /** Rename a team. */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/teams/{teamId}/epics": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team identifier. */
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        /**
         * List the epics belonging to a team.
         * @description Convenience listing used to populate the ticket epic dropdown (same-team only).
         */
        get: operations["listTeamEpics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/epics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List epics, optionally filtered by team. */
        get: operations["listEpics"];
        put?: never;
        /**
         * Create an epic within a team.
         * @description The team is set at creation and is immutable thereafter.
         */
        post: operations["createEpic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/epics/{epicId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Epic identifier. */
                epicId: components["parameters"]["EpicId"];
            };
            cookie?: never;
        };
        /** Get a single epic. */
        get: operations["getEpic"];
        put?: never;
        post?: never;
        /**
         * Delete an epic.
         * @description Fails with 409 if any ticket still references it.
         */
        delete: operations["deleteEpic"];
        options?: never;
        head?: never;
        /**
         * Update an epic's title/description.
         * @description The team association cannot be changed.
         */
        patch: operations["updateEpic"];
        trace?: never;
    };
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tickets for a team's board, with filters and title search.
         * @description Returns the tickets for the selected team's Kanban board. Optional filters (type, epicId, q) are AND-combined. `q` is a case-insensitive substring match over the ticket title. Results are ordered by `modifiedAt` descending (most-recently-modified first) so callers can bucket them into the five state columns.
         */
        get: operations["listTickets"];
        put?: never;
        /**
         * Create a ticket.
         * @description `createdBy` and timestamps are server-set. If `epicId` is provided it must reference an epic in the same team, else 400 EPIC_TEAM_MISMATCH.
         */
        post: operations["createTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{ticketId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket identifier. */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** Get a ticket with all fields. */
        get: operations["getTicket"];
        put?: never;
        post?: never;
        /** Delete a ticket (cascades to its comments). */
        delete: operations["deleteTicket"];
        options?: never;
        head?: never;
        /**
         * Update a ticket (type, team, epic, title, body, state).
         * @description Partial update. `modifiedAt` advances only when a field actually changes; saving unchanged values must not advance it. Changing `team` requires a compatible `epicId` (same team) or `epicId: null`. Any-to-any state moves are allowed. This operation also persists drag-and-drop state changes.
         */
        patch: operations["updateTicket"];
        trace?: never;
    };
    "/tickets/{ticketId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket identifier. */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        /** List a ticket's comments, oldest first. */
        get: operations["listComments"];
        put?: never;
        /**
         * Add a comment to a ticket.
         * @description Author is the authenticated user; `createdAt` is server-set. Adding a comment does NOT change the ticket's `modifiedAt`.
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Opaque stable identifier (UUID or DB-numeric string).
         * @example 3f2504e0-4f89-41d3-9a0c-0305e82c3301
         */
        Id: string;
        /**
         * @description Ticket type label (no behavioral difference).
         * @enum {string}
         */
        TicketType: "bug" | "feature" | "fix";
        /**
         * @description Canonical workflow state (UI renders human-readable labels).
         * @enum {string}
         */
        TicketState: "new" | "ready_for_implementation" | "in_progress" | "ready_for_acceptance" | "done";
        /** @description Shared error envelope for all non-2xx responses. */
        Error: {
            /**
             * @description Stable machine-readable error code (SCREAMING_SNAKE_CASE).
             * @example VALIDATION_ERROR
             */
            code: string;
            /** @description Human-readable, safe-to-expose message. */
            message: string;
            /** @description Optional structured context. */
            details?: {
                [key: string]: unknown;
            };
        };
        MessageResponse: {
            message: string;
        };
        SignupRequest: {
            /**
             * Format: email
             * @description Email address (trimmed, compared case-insensitively).
             */
            email: string;
            /** @description Plaintext password (hashed server-side; never stored raw). */
            password: string;
        };
        SignupResponse: {
            /** @description Confirmation that a verification email was sent. */
            message: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            /** @description Bearer JWT to send in the Authorization header. */
            token: string;
            user: components["schemas"]["User"];
        };
        ResendVerificationRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Public representation of an account. */
        User: {
            id: components["schemas"]["Id"];
            /** Format: email */
            email: string;
            emailVerified: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        Team: {
            id: components["schemas"]["Id"];
            /** @description Team name (non-empty after trim; unique case-insensitively). */
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            modifiedAt: string;
        };
        TeamCreateRequest: {
            name: string;
        };
        TeamUpdateRequest: {
            name: string;
        };
        Epic: {
            id: components["schemas"]["Id"];
            teamId: components["schemas"]["Id"];
            /** @description Epic title (non-empty after trim). */
            title: string;
            /** @description Optional description. */
            description?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            modifiedAt: string;
        };
        EpicCreateRequest: {
            teamId: components["schemas"]["Id"];
            title: string;
            description?: string | null;
        };
        /** @description Team association is immutable and cannot be updated. */
        EpicUpdateRequest: {
            title?: string;
            description?: string | null;
        };
        Ticket: {
            id: components["schemas"]["Id"];
            teamId: components["schemas"]["Id"];
            type: components["schemas"]["TicketType"];
            state: components["schemas"]["TicketState"];
            /** @description Referenced epic (same team), or null. */
            epicId: components["schemas"]["Id"] | null;
            title: string;
            /** @description Plain text or Markdown; non-empty. */
            body: string;
            createdBy: components["schemas"]["Id"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            modifiedAt: string;
        };
        TicketCreateRequest: {
            teamId: components["schemas"]["Id"];
            type: components["schemas"]["TicketType"];
            /** @description Optional; defaults to `new` when omitted. */
            state?: components["schemas"]["TicketState"];
            /** @description Optional epic from the same team, or null. */
            epicId?: components["schemas"]["Id"] | null;
            title: string;
            body: string;
        };
        /** @description Partial update; at least one property must be present. */
        TicketUpdateRequest: {
            teamId?: components["schemas"]["Id"];
            type?: components["schemas"]["TicketType"];
            state?: components["schemas"]["TicketState"];
            epicId?: components["schemas"]["Id"] | null;
            title?: string;
            body?: string;
        };
        Comment: {
            id: components["schemas"]["Id"];
            ticketId: components["schemas"]["Id"];
            authorId: components["schemas"]["Id"];
            body: string;
            /** Format: date-time */
            createdAt: string;
        };
        CommentCreateRequest: {
            body: string;
        };
    };
    responses: {
        /** @description Validation error (invalid body, params, or enum value). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION_ERROR",
                 *       "message": "Request failed validation.",
                 *       "details": {
                 *         "field": "title"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "UNAUTHORIZED",
                 *       "message": "Authentication required."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authenticated but not permitted (e.g. unverified account). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "EMAIL_NOT_VERIFIED",
                 *       "message": "Please verify your email before using the app."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The requested resource was not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "NOT_FOUND",
                 *       "message": "Resource does not exist."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Team identifier. */
        TeamId: components["schemas"]["Id"];
        /** @description Epic identifier. */
        EpicId: components["schemas"]["Id"];
        /** @description Ticket identifier. */
        TicketId: components["schemas"]["Id"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Account created; verification email dispatched. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email already registered. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EMAIL_TAKEN",
                     *       "message": "An account with this email already exists."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; bearer token issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid email or password. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "INVALID_CREDENTIALS",
                     *       "message": "Invalid email or password."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Account exists but email is not verified. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EMAIL_NOT_VERIFIED",
                     *       "message": "Please verify your email before signing in."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. No content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    verifyEmail: {
        parameters: {
            query: {
                /** @description Single-use email-verification token. */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification succeeded; redirect to the login screen. */
            302: {
                headers: {
                    /** @description Absolute URL of the login screen (`${APP_BASE_URL}/login`). */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token missing, malformed, expired, or already used. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    resendVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            /** @description If the account exists and is unverified, a new email was sent. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Teams, ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreateRequest"];
            };
        };
        responses: {
            /** @description Team created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A team with this name already exists (case-insensitive). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TEAM_NAME_TAKEN",
                     *       "message": "A team with this name already exists."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team identifier. */
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team identifier. */
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Team deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Team still has tickets or epics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TEAM_HAS_DEPENDENTS",
                     *       "message": "This team has tickets or epics and cannot be deleted."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team identifier. */
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamUpdateRequest"];
            };
        };
        responses: {
            /** @description Team updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A team with this name already exists (case-insensitive). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TEAM_NAME_TAKEN",
                     *       "message": "A team with this name already exists."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTeamEpics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Team identifier. */
                teamId: components["parameters"]["TeamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Epics for the team, ordered by title. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Epic"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listEpics: {
        parameters: {
            query?: {
                /** @description Restrict to epics belonging to this team. */
                teamId?: components["schemas"]["Id"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Epics, ordered by title. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Epic"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createEpic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpicCreateRequest"];
            };
        };
        responses: {
            /** @description Epic created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Epic"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Referenced team does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TEAM_NOT_FOUND",
                     *       "message": "Team does not exist."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getEpic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Epic identifier. */
                epicId: components["parameters"]["EpicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The epic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Epic"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteEpic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Epic identifier. */
                epicId: components["parameters"]["EpicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Epic deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Epic is still referenced by one or more tickets. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "EPIC_REFERENCED",
                     *       "message": "This epic is referenced by tickets and cannot be deleted."
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateEpic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Epic identifier. */
                epicId: components["parameters"]["EpicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpicUpdateRequest"];
            };
        };
        responses: {
            /** @description Epic updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Epic"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listTickets: {
        parameters: {
            query: {
                /** @description The team whose board to list. */
                teamId: components["schemas"]["Id"];
                /** @description Filter by ticket type. */
                type?: components["schemas"]["TicketType"];
                /** @description Filter by referenced epic. */
                epicId?: components["schemas"]["Id"];
                /** @description Case-insensitive substring search over the ticket title. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching tickets, most-recently-modified first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketCreateRequest"];
            };
        };
        responses: {
            /** @description Ticket created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation error, invalid enum, or cross-team epic. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Referenced team or epic does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket identifier. */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ticket. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket identifier. */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticket and its comments deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket identifier. */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketUpdateRequest"];
            };
        };
        responses: {
            /** @description Ticket updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticket"];
                };
            };
            /** @description Validation error, invalid enum, or cross-team epic. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket identifier. */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Comments in chronological order (oldest first). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ticket identifier. */
                ticketId: components["parameters"]["TicketId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommentCreateRequest"];
            };
        };
        responses: {
            /** @description Comment created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
