/**
 * AUTO-GENERATED by packages/shared/scripts/build-schemas.mjs from contracts/openapi.yaml.
 * DO NOT EDIT BY HAND (see ADR-0006). Regenerate with: npm run gen:schemas
 *
 * Fastify/Ajv-shaped request/response JSON Schemas keyed by OpenAPI operationId.
 */
import type { RouteSchemas } from './index.js';

export const schemas: Record<string, RouteSchemas> = {
  "signup": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "description": "Email address (trimmed, compared case-insensitively).",
          "minLength": 3,
          "maxLength": 254
        },
        "password": {
          "type": "string",
          "description": "Plaintext password (hashed server-side; never stored raw).",
          "minLength": 8,
          "maxLength": 200
        }
      }
    },
    "response": {
      "201": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "type": "string",
            "description": "Confirmation that a verification email was sent."
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "409": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "login": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "email",
        "password"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "minLength": 3,
          "maxLength": 254
        },
        "password": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        }
      }
    },
    "response": {
      "200": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "token",
          "user"
        ],
        "properties": {
          "token": {
            "type": "string",
            "description": "Bearer JWT to send in the Authorization header."
          },
          "user": {
            "type": "object",
            "description": "Public representation of an account.",
            "additionalProperties": false,
            "required": [
              "id",
              "email",
              "emailVerified",
              "createdAt"
            ],
            "properties": {
              "id": {
                "type": "string",
                "description": "Opaque stable identifier (UUID or DB-numeric string).",
                "minLength": 1,
                "examples": [
                  "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
                ]
              },
              "email": {
                "type": "string",
                "format": "email"
              },
              "emailVerified": {
                "type": "boolean"
              },
              "createdAt": {
                "type": "string",
                "format": "date-time"
              }
            }
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "logout": {
    "response": {
      "204": {},
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "verifyEmail": {
    "querystring": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "token"
      ],
      "additionalProperties": true
    },
    "response": {
      "302": {},
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "resendVerification": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "email"
      ],
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "minLength": 3,
          "maxLength": 254
        }
      }
    },
    "response": {
      "202": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "message"
        ],
        "properties": {
          "message": {
            "type": "string"
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "listTeams": {
    "response": {
      "200": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "name",
            "createdAt",
            "modifiedAt"
          ],
          "properties": {
            "id": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "name": {
              "type": "string",
              "description": "Team name (non-empty after trim; unique case-insensitively).",
              "minLength": 1,
              "maxLength": 120
            },
            "createdAt": {
              "type": "string",
              "format": "date-time"
            },
            "modifiedAt": {
              "type": "string",
              "format": "date-time"
            }
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "createTeam": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 120
        }
      }
    },
    "response": {
      "201": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "name",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "name": {
            "type": "string",
            "description": "Team name (non-empty after trim; unique case-insensitively).",
            "minLength": 1,
            "maxLength": 120
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "409": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "getTeam": {
    "params": {
      "type": "object",
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "teamId"
      ],
      "additionalProperties": false
    },
    "response": {
      "200": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "name",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "name": {
            "type": "string",
            "description": "Team name (non-empty after trim; unique case-insensitively).",
            "minLength": 1,
            "maxLength": 120
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "updateTeam": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1,
          "maxLength": 120
        }
      }
    },
    "params": {
      "type": "object",
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "teamId"
      ],
      "additionalProperties": false
    },
    "response": {
      "200": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "name",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "name": {
            "type": "string",
            "description": "Team name (non-empty after trim; unique case-insensitively).",
            "minLength": 1,
            "maxLength": 120
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "409": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "deleteTeam": {
    "params": {
      "type": "object",
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "teamId"
      ],
      "additionalProperties": false
    },
    "response": {
      "204": {},
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "409": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "listTeamEpics": {
    "params": {
      "type": "object",
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "teamId"
      ],
      "additionalProperties": false
    },
    "response": {
      "200": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "teamId",
            "title",
            "createdAt",
            "modifiedAt"
          ],
          "properties": {
            "id": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "teamId": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "title": {
              "type": "string",
              "description": "Epic title (non-empty after trim).",
              "minLength": 1,
              "maxLength": 200
            },
            "description": {
              "type": [
                "string",
                "null"
              ],
              "description": "Optional description.",
              "maxLength": 5000
            },
            "createdAt": {
              "type": "string",
              "format": "date-time"
            },
            "modifiedAt": {
              "type": "string",
              "format": "date-time"
            }
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "listEpics": {
    "querystring": {
      "type": "object",
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "additionalProperties": true
    },
    "response": {
      "200": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "teamId",
            "title",
            "createdAt",
            "modifiedAt"
          ],
          "properties": {
            "id": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "teamId": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "title": {
              "type": "string",
              "description": "Epic title (non-empty after trim).",
              "minLength": 1,
              "maxLength": 200
            },
            "description": {
              "type": [
                "string",
                "null"
              ],
              "description": "Optional description.",
              "maxLength": 5000
            },
            "createdAt": {
              "type": "string",
              "format": "date-time"
            },
            "modifiedAt": {
              "type": "string",
              "format": "date-time"
            }
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "createEpic": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "teamId",
        "title"
      ],
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        },
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "description": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 5000
        }
      }
    },
    "response": {
      "201": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "teamId",
          "title",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "teamId": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "title": {
            "type": "string",
            "description": "Epic title (non-empty after trim).",
            "minLength": 1,
            "maxLength": 200
          },
          "description": {
            "type": [
              "string",
              "null"
            ],
            "description": "Optional description.",
            "maxLength": 5000
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "getEpic": {
    "params": {
      "type": "object",
      "properties": {
        "epicId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "epicId"
      ],
      "additionalProperties": false
    },
    "response": {
      "200": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "teamId",
          "title",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "teamId": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "title": {
            "type": "string",
            "description": "Epic title (non-empty after trim).",
            "minLength": 1,
            "maxLength": 200
          },
          "description": {
            "type": [
              "string",
              "null"
            ],
            "description": "Optional description.",
            "maxLength": 5000
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "updateEpic": {
    "body": {
      "type": "object",
      "description": "Team association is immutable and cannot be updated.",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "description": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 5000
        }
      }
    },
    "params": {
      "type": "object",
      "properties": {
        "epicId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "epicId"
      ],
      "additionalProperties": false
    },
    "response": {
      "200": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "teamId",
          "title",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "teamId": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "title": {
            "type": "string",
            "description": "Epic title (non-empty after trim).",
            "minLength": 1,
            "maxLength": 200
          },
          "description": {
            "type": [
              "string",
              "null"
            ],
            "description": "Optional description.",
            "maxLength": 5000
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "deleteEpic": {
    "params": {
      "type": "object",
      "properties": {
        "epicId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "epicId"
      ],
      "additionalProperties": false
    },
    "response": {
      "204": {},
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "409": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "listTickets": {
    "querystring": {
      "type": "object",
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        },
        "type": {
          "type": "string",
          "description": "Ticket type label (no behavioral difference).",
          "enum": [
            "bug",
            "feature",
            "fix"
          ]
        },
        "epicId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        },
        "q": {
          "type": "string",
          "maxLength": 200
        }
      },
      "required": [
        "teamId"
      ],
      "additionalProperties": true
    },
    "response": {
      "200": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "teamId",
            "type",
            "state",
            "epicId",
            "title",
            "body",
            "createdBy",
            "createdAt",
            "modifiedAt"
          ],
          "properties": {
            "id": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "teamId": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "type": {
              "type": "string",
              "description": "Ticket type label (no behavioral difference).",
              "enum": [
                "bug",
                "feature",
                "fix"
              ]
            },
            "state": {
              "type": "string",
              "description": "Canonical workflow state (UI renders human-readable labels).",
              "enum": [
                "new",
                "ready_for_implementation",
                "in_progress",
                "ready_for_acceptance",
                "done"
              ]
            },
            "epicId": {
              "oneOf": [
                {
                  "type": "string",
                  "description": "Opaque stable identifier (UUID or DB-numeric string).",
                  "minLength": 1,
                  "examples": [
                    "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
                  ]
                },
                {
                  "type": "null"
                }
              ],
              "description": "Referenced epic (same team), or null."
            },
            "title": {
              "type": "string",
              "minLength": 1,
              "maxLength": 200
            },
            "body": {
              "type": "string",
              "description": "Plain text or Markdown; non-empty.",
              "minLength": 1,
              "maxLength": 20000
            },
            "createdBy": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "createdAt": {
              "type": "string",
              "format": "date-time"
            },
            "modifiedAt": {
              "type": "string",
              "format": "date-time"
            }
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "createTicket": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "teamId",
        "type",
        "title",
        "body"
      ],
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        },
        "type": {
          "type": "string",
          "description": "Ticket type label (no behavioral difference).",
          "enum": [
            "bug",
            "feature",
            "fix"
          ]
        },
        "state": {
          "type": "string",
          "description": "Optional; defaults to `new` when omitted.",
          "enum": [
            "new",
            "ready_for_implementation",
            "in_progress",
            "ready_for_acceptance",
            "done"
          ]
        },
        "epicId": {
          "oneOf": [
            {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            {
              "type": "null"
            }
          ],
          "description": "Optional epic from the same team, or null."
        },
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "body": {
          "type": "string",
          "minLength": 1,
          "maxLength": 20000
        }
      }
    },
    "response": {
      "201": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "teamId",
          "type",
          "state",
          "epicId",
          "title",
          "body",
          "createdBy",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "teamId": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "type": {
            "type": "string",
            "description": "Ticket type label (no behavioral difference).",
            "enum": [
              "bug",
              "feature",
              "fix"
            ]
          },
          "state": {
            "type": "string",
            "description": "Canonical workflow state (UI renders human-readable labels).",
            "enum": [
              "new",
              "ready_for_implementation",
              "in_progress",
              "ready_for_acceptance",
              "done"
            ]
          },
          "epicId": {
            "oneOf": [
              {
                "type": "string",
                "description": "Opaque stable identifier (UUID or DB-numeric string).",
                "minLength": 1,
                "examples": [
                  "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Referenced epic (same team), or null."
          },
          "title": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200
          },
          "body": {
            "type": "string",
            "description": "Plain text or Markdown; non-empty.",
            "minLength": 1,
            "maxLength": 20000
          },
          "createdBy": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "getTicket": {
    "params": {
      "type": "object",
      "properties": {
        "ticketId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "ticketId"
      ],
      "additionalProperties": false
    },
    "response": {
      "200": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "teamId",
          "type",
          "state",
          "epicId",
          "title",
          "body",
          "createdBy",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "teamId": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "type": {
            "type": "string",
            "description": "Ticket type label (no behavioral difference).",
            "enum": [
              "bug",
              "feature",
              "fix"
            ]
          },
          "state": {
            "type": "string",
            "description": "Canonical workflow state (UI renders human-readable labels).",
            "enum": [
              "new",
              "ready_for_implementation",
              "in_progress",
              "ready_for_acceptance",
              "done"
            ]
          },
          "epicId": {
            "oneOf": [
              {
                "type": "string",
                "description": "Opaque stable identifier (UUID or DB-numeric string).",
                "minLength": 1,
                "examples": [
                  "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Referenced epic (same team), or null."
          },
          "title": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200
          },
          "body": {
            "type": "string",
            "description": "Plain text or Markdown; non-empty.",
            "minLength": 1,
            "maxLength": 20000
          },
          "createdBy": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "updateTicket": {
    "body": {
      "type": "object",
      "description": "Partial update; at least one property must be present.",
      "additionalProperties": false,
      "minProperties": 1,
      "properties": {
        "teamId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        },
        "type": {
          "type": "string",
          "description": "Ticket type label (no behavioral difference).",
          "enum": [
            "bug",
            "feature",
            "fix"
          ]
        },
        "state": {
          "type": "string",
          "description": "Canonical workflow state (UI renders human-readable labels).",
          "enum": [
            "new",
            "ready_for_implementation",
            "in_progress",
            "ready_for_acceptance",
            "done"
          ]
        },
        "epicId": {
          "oneOf": [
            {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            {
              "type": "null"
            }
          ]
        },
        "title": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200
        },
        "body": {
          "type": "string",
          "minLength": 1,
          "maxLength": 20000
        }
      }
    },
    "params": {
      "type": "object",
      "properties": {
        "ticketId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "ticketId"
      ],
      "additionalProperties": false
    },
    "response": {
      "200": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "teamId",
          "type",
          "state",
          "epicId",
          "title",
          "body",
          "createdBy",
          "createdAt",
          "modifiedAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "teamId": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "type": {
            "type": "string",
            "description": "Ticket type label (no behavioral difference).",
            "enum": [
              "bug",
              "feature",
              "fix"
            ]
          },
          "state": {
            "type": "string",
            "description": "Canonical workflow state (UI renders human-readable labels).",
            "enum": [
              "new",
              "ready_for_implementation",
              "in_progress",
              "ready_for_acceptance",
              "done"
            ]
          },
          "epicId": {
            "oneOf": [
              {
                "type": "string",
                "description": "Opaque stable identifier (UUID or DB-numeric string).",
                "minLength": 1,
                "examples": [
                  "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
                ]
              },
              {
                "type": "null"
              }
            ],
            "description": "Referenced epic (same team), or null."
          },
          "title": {
            "type": "string",
            "minLength": 1,
            "maxLength": 200
          },
          "body": {
            "type": "string",
            "description": "Plain text or Markdown; non-empty.",
            "minLength": 1,
            "maxLength": 20000
          },
          "createdBy": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "deleteTicket": {
    "params": {
      "type": "object",
      "properties": {
        "ticketId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "ticketId"
      ],
      "additionalProperties": false
    },
    "response": {
      "204": {},
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "listComments": {
    "params": {
      "type": "object",
      "properties": {
        "ticketId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "ticketId"
      ],
      "additionalProperties": false
    },
    "response": {
      "200": {
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "id",
            "ticketId",
            "authorId",
            "body",
            "createdAt"
          ],
          "properties": {
            "id": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "ticketId": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "authorId": {
              "type": "string",
              "description": "Opaque stable identifier (UUID or DB-numeric string).",
              "minLength": 1,
              "examples": [
                "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
              ]
            },
            "body": {
              "type": "string",
              "minLength": 1,
              "maxLength": 20000
            },
            "createdAt": {
              "type": "string",
              "format": "date-time"
            }
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "createComment": {
    "body": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "body"
      ],
      "properties": {
        "body": {
          "type": "string",
          "minLength": 1,
          "maxLength": 20000
        }
      }
    },
    "params": {
      "type": "object",
      "properties": {
        "ticketId": {
          "type": "string",
          "description": "Opaque stable identifier (UUID or DB-numeric string).",
          "minLength": 1,
          "examples": [
            "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
          ]
        }
      },
      "required": [
        "ticketId"
      ],
      "additionalProperties": false
    },
    "response": {
      "201": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "ticketId",
          "authorId",
          "body",
          "createdAt"
        ],
        "properties": {
          "id": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "ticketId": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "authorId": {
            "type": "string",
            "description": "Opaque stable identifier (UUID or DB-numeric string).",
            "minLength": 1,
            "examples": [
              "3f2504e0-4f89-41d3-9a0c-0305e82c3301"
            ]
          },
          "body": {
            "type": "string",
            "minLength": 1,
            "maxLength": 20000
          },
          "createdAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "400": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "401": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "403": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      },
      "404": {
        "type": "object",
        "description": "Shared error envelope for all non-2xx responses.",
        "additionalProperties": false,
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "string",
            "description": "Stable machine-readable error code (SCREAMING_SNAKE_CASE).",
            "examples": [
              "VALIDATION_ERROR"
            ]
          },
          "message": {
            "type": "string",
            "description": "Human-readable, safe-to-expose message."
          },
          "details": {
            "type": "object",
            "description": "Optional structured context.",
            "additionalProperties": true
          }
        }
      }
    }
  }
} as const;
