#!/usr/bin/env node
/**
 * build-schemas.mjs — extract Fastify/Ajv-shaped JSON Schemas from contracts/openapi.yaml.
 *
 * For every operation that declares an `operationId`, emit a RouteSchemas record:
 *   { body?, params?, querystring?, response: { <status>: schema } }
 * keyed by operationId. All `$ref`s into `#/components/...` are fully inlined so each
 * emitted schema is self-contained and consumable directly by Fastify's Ajv.
 *
 * Output: packages/shared/src/schemas.ts (generated — do not hand-edit; see ADR-0006).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import yaml from 'js-yaml';

const here = dirname(fileURLToPath(import.meta.url));
const specPath = resolve(here, '../../../contracts/openapi.yaml');
const outPath = resolve(here, '../src/schemas.ts');

const doc = yaml.load(readFileSync(specPath, 'utf8'));

/** Resolve a local JSON Pointer ($ref like `#/components/schemas/Foo`) against the doc. */
function resolvePointer(ref) {
  if (!ref.startsWith('#/')) throw new Error(`Only local refs supported: ${ref}`);
  const parts = ref.slice(2).split('/').map((p) => p.replace(/~1/g, '/').replace(/~0/g, '~'));
  let node = doc;
  for (const part of parts) {
    node = node?.[part];
    if (node === undefined) throw new Error(`Unresolvable ref: ${ref}`);
  }
  return node;
}

/** Deep-clone while inlining every `$ref` to `#/components/...`. Our schemas are acyclic. */
function deref(node, seen = new Set()) {
  if (Array.isArray(node)) return node.map((n) => deref(n, seen));
  if (node && typeof node === 'object') {
    if (typeof node.$ref === 'string') {
      const ref = node.$ref;
      if (seen.has(ref)) throw new Error(`Cyclic ref detected: ${ref}`);
      const resolved = resolvePointer(ref);
      const next = new Set(seen);
      next.add(ref);
      const inlined = deref(resolved, next);
      // Merge any sibling keys of the $ref (rare) over the inlined target.
      const siblings = { ...node };
      delete siblings.$ref;
      return { ...inlined, ...deref(siblings, seen) };
    }
    const out = {};
    for (const [k, v] of Object.entries(node)) out[k] = deref(v, seen);
    return out;
  }
  return node;
}

/** Build an object JSON Schema from a list of OpenAPI parameters of a given `in`. */
function paramsToSchema(params, location) {
  const picked = params.filter((p) => p.in === location);
  if (picked.length === 0) return undefined;
  const properties = {};
  const required = [];
  for (const p of picked) {
    properties[p.name] = deref(p.schema ?? {});
    if (p.required) required.push(p.name);
  }
  const schema = { type: 'object', properties };
  if (required.length) schema.required = required;
  // Path params are always fully specified; query allows unknown-but-ignored extras.
  schema.additionalProperties = location === 'path' ? false : true;
  return schema;
}

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'];
const result = {};

for (const [path, pathItem] of Object.entries(doc.paths ?? {})) {
  const pathParams = (pathItem.parameters ?? []).map((p) => deref(p));
  for (const method of HTTP_METHODS) {
    const op = pathItem[method];
    if (!op || !op.operationId) continue;

    const opParams = (op.parameters ?? []).map((p) => deref(p));
    const allParams = [...pathParams, ...opParams];

    const route = {};

    const bodySchema = op.requestBody?.content?.['application/json']?.schema;
    if (bodySchema) route.body = deref(bodySchema);

    const params = paramsToSchema(allParams, 'path');
    if (params) route.params = params;

    const querystring = paramsToSchema(allParams, 'query');
    if (querystring) route.querystring = querystring;

    const response = {};
    for (const [status, resObj] of Object.entries(op.responses ?? {})) {
      const derefRes = deref(resObj);
      const schema = derefRes?.content?.['application/json']?.schema;
      const code = Number(status);
      if (Number.isNaN(code)) continue; // skip 'default' etc.
      // No JSON body (204/302): emit an empty schema so the status is still declared.
      response[code] = schema ?? {};
    }
    route.response = response;

    result[op.operationId] = route;
  }
}

const banner = `/**
 * AUTO-GENERATED by packages/shared/scripts/build-schemas.mjs from contracts/openapi.yaml.
 * DO NOT EDIT BY HAND (see ADR-0006). Regenerate with: npm run gen:schemas
 *
 * Fastify/Ajv-shaped request/response JSON Schemas keyed by OpenAPI operationId.
 */
import type { RouteSchemas } from './index.js';

export const schemas: Record<string, RouteSchemas> = ${JSON.stringify(result, null, 2)} as const;
`;

writeFileSync(outPath, banner);
console.log(`Wrote ${Object.keys(result).length} operation schemas to ${outPath}`);
